# Generated by Django 4.1 on 2022-08-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxsulot_nomi', models.CharField(max_length=150)),
                ('tarkibi', models.TextField()),
                ('narxi', models.CharField(max_length=14)),
                ('img', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
